//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class branches
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<int> principle_contacts_id { get; set; }
        public Nullable<int> contact_a_contacts_id { get; set; }
        public Nullable<int> contact_b_contacts_id { get; set; }
    }
}
