//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public int student_concacts_id { get; set; }
        public string grade { get; set; }
        public string @class { get; set; }
        public string health_issues { get; set; }
        public string pick_up_options { get; set; }
        public bool gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public bool is_active { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> parent_a_contacts_id { get; set; }
        public Nullable<int> parent_b_contacts_id { get; set; }
    }
}
