//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class students
    {
        [Key, ForeignKey("contacts")]
        public int student_concacts_id { get; set; }
        public string grade { get; set; }
        public string @class { get; set; }
        public string health_issues { get; set; }
        public string pick_up_options { get; set; }
        public bool gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
    
        public virtual contacts contacts { get; set; }
    }
}
