//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class students_checkin
    {
        public int id { get; set; }
        public int student_concacts_id { get; set; }
        public int set_coundler_id { get; set; }
        public System.DateTime hour_date { get; set; }
    }
}
