//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class counslers
    {
        public int counsler_concacts_id { get; set; }
        public bool gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public bool is_active { get; set; }
        public string allowed_branches { get; set; }
        public string usernmae { get; set; }
    }
}
