//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string grade { get; set; }
        public Nullable<int> branch_id { get; set; }
        public string @class { get; set; }
        public string health_issues { get; set; }
        public string pick_up_options { get; set; }
        public bool gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public bool is_active { get; set; }
        public string phone_mobile { get; set; }
        public string phone_home { get; set; }
        public string address { get; set; }
        public string parent_a_email { get; set; }
        public string parent_a_phone_mobile { get; set; }
        public string parent_a_first_name { get; set; }
        public string parent_a_last_name { get; set; }
        public string parent_b_email { get; set; }
        public string parent_b_phone_mobile { get; set; }
        public string parent_b_first_name { get; set; }
        public string parent_b_last_name { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string image { get; set; }
    }
}
