//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_pickup
    {
        public int id { get; set; }
        public string eng_name { get; set; }
        public string heb_name { get; set; }
        public string where { get; set; }
        public int group_id { get; set; }
    }
}
