//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class counslers
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public bool gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public bool is_active { get; set; }
        public string allowed_branches { get; set; }
        public string usernmae { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string phone_mobile { get; set; }
        public string phone_home { get; set; }
        public string email_1 { get; set; }
        public string email_2 { get; set; }
        public string address { get; set; }
        public string image { get; set; }
        public string default_grade { get; set; }
        public string default_class { get; set; }
    }
}
