//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class counslers_schedule
    {
        public int id { get; set; }
        public int counsler_id { get; set; }
        public int day { get; set; }
        public int hour_num { get; set; }
        public string activity { get; set; }
        public string location { get; set; }
        public string group { get; set; }
        public string comment { get; set; }
        public string hour_desc_ { get; set; }
    }
}
