//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pickmepleasedbEntities : DbContext
    {
        public pickmepleasedbEntities()
            : base("name=pickmepleasedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<students_checkin> students_checkin { get; set; }
        public DbSet<students_pickup> students_pickup { get; set; }
        public DbSet<branches> branches { get; set; }
        public DbSet<contacts> contacts { get; set; }
        public DbSet<counslers> counslers { get; set; }
        public DbSet<students> students { get; set; }
    }
}
