//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class students_pickup
    {
        public int id { get; set; }
        public int student_concacts_id { get; set; }
        public bool is_by_other { get; set; }
        public string picker_name { get; set; }
        public int set_coundler_id { get; set; }
        public System.DateTime hour_date { get; set; }
    }
}
